### ISSUE TITLE
getting not found error

### ISSUE THREAD

**Issue by anantsparrow** [austinginder/whois#1]
![image](https://github.com/austinginder/whois/assets/38394340/4387d32d-0884-469d-9b15-7a2c2b6decdb)

**Comment by austinginder** [comment]
This would happen if the output of `whois anchor.host` is empty. On your computer try opening a terminal and running that command manually. Should looks like the following. Some internet provider may block whois lookups. Also you might be missing the `whois` command. On Mac with [homebrew](https://brew.sh) you can install with `brew install whois`.

<img width="1308" alt="Screenshot 2024-02-17 at 2 06 09 PM" src="https://github.com/austinginder/whois/assets/110346/6318e1d4-19ea-49ad-b650-f3a3bfd0e597">
